### ISSUE TITLE
main mounter også lite-folders

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/servere#3]
Se vagrant up-log og listen over mounted shared folders:
https://gist.github.com/AsgeirSH/3df2748d538146adf9ae31e5fd3ae34d

**Comment by mariusmandal** [comment]
Har lest over koden @AsgeirSH, og kommer frem til at den registrerer mounts på alle maskiner når vi initierer config. Der har jeg også lagt på en echo, som forteller at mount point er registrert.
Men, når vagrant faktisk fyrer opp boksen, så er det kun riktige mount points som setter opp.
Jeg lukker derfor denne jeg, og så må du gjerne åpne den om jeg har misforstått, så skal jeg prøve igjen 😊
